// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mcsd.Core.Library.DataAccess.Entity
{
    public partial class ContactFormEntity
    {
        public int      id              { get; set; }
        public string   Name            { get; set; }
        public string   field_1         { get; set; }
        public string   field_2         { get; set; }
        public DateTime field_3         { get; set; }
    }
}