// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mcsd.Core.Library
{
    public partial class Pagina
    {
        public int IdPagina { get; set; }
        public string NombrePagina { get; set; }
    }
}