// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mcsd.Core.Library
{
    public partial class accessLogs
    {
        public int ID_column { get; set; }
        public string PageName { get; set; }
        public DateTime AccessDate { get; set; }
        public string IpValue { get; set; }
        public byte? LogType { get; set; }
    }
}