// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace mcsd.Core.Library
{
    public partial class Persona
    {
        public int ID_column { get; set; }
        public string NombreCompleto { get; set; }
        public string ProfesionOficio { get; set; }
        public string Ciudad { get; set; }
    }
}